@startuml
title die wichtigsten Interaktionen mit Dokumenten

participant Client as c
participant "Dokumente API" as api

== Upload des Dokuments ==
c -> api: POST /dokumente
note right: Dokument wird ggf in PDF gewandelt
api --> c: 201 Created (Dokument)

== Kategorisierung des Dokuments starten ==
c -> api: POST /dokumente/{dokumentId}/kategorisierung
api --> c: 200 OK

== Kategorisierungsstatus des Dokuments abfragen ==
loop
c -> api: GET /dokumente/{dokumentId}/kategorisierung
api --> c: 200 OK
note right
   sobald der Status auf DONE wechselt,
   stehen die **Seiten** des Dokuments zur Verfügung
end note
end

== Download des Dokuments ==
c -> api: GET /dokumente/{dokumentId}/content
api --> c: 200 OK

@enduml
