@startuml
title the most important interactions with pages

participant Client as c
participant "Unterlagen API" as api

== get metadata of all pages of a document ==
c -> api: GET /dokumente/{dokumentId}/seiten
api --> c: 200 OK

== get metadata of all pages of an operation ==
c -> api: GET /dokumente/seiten vorgangsNummer
api --> c: 200 OK

== move pages to archive ==
c -> api: PUT /dokumente/archiv (seiten)
api --> c: 200 OK

== mark pages as checked ==
c -> api: PUT /dokumente/archiv (seiten)
api --> c: 200 OK

== assign pages (category and set assignment) ==
c -> api: PUT /dokumente/zuordnung/{kategorie} (bezug, seiten)
api --> c: 200 OK


@enduml
