@startuml
title Unterlagen zu einem Vorgang (ab API v.0.16)

participant Client as c
participant "Dokumente API" as api

== Unterlagen eines Dokuments abrufen ==
c -> api: GET /dokumente/{dokumentId}/unterlagen
api --> c: 200 OK ([Unterlage])

== Unterlagen eines Vorgangs abrufen ==

c -> api: GET /dokumente/unterlagen?vorgangsNummer={vorgangsNummer}
api --> c: 200 OK ([Unterlage])

== Korrektur der Unterlagen ==

c -> api: PUT /dokumente/unterlagen ([Unterlage])
api --> c: 200 OK ([Unterlage])

== Freigabe von Unterlagen ==
c -> api: POST /dokumente/freigabe (antragsNummer, [Unterlage])
api --> c: 201 OK ([FreigegebeneUnterlage])

@enduml