@startuml
title the most important interactions with shared documents

participant Client as c
participant "Unterlagen API" as api

== sharing of documents ==
c -> api: POST /dokumente/freigabe (antragsNummer, seiten)
api --> c: 201 CREATED

== get metadata of document ==
c -> api: GET /dokumente/freigabe/{id}
api --> c: 200 OK

== get metadata for all documents in an application ==
c -> api: GET /dokumente/freigabe (antragsNummer)
api --> c: 200 OK

== get the contents of a document ==
c -> api: GET /dokumente/freigabe/{id}/content
api --> c: 200 OK

== get content of all documents of an application ==
c -> api: GET /dokumente/freigaben/content (antragsNummer)
api --> c: 200 OK

== get the retrieval state of a document \n Has the document arrived at the product provider? ==
c -> api: GET /dokumente/freigabe/{id}/status
api --> c: 200 OK


@enduml
